tinymce.addI18n('no',{
"Redo": "Gjør om",
"Undo": "Angre",
"Cut": "Kutt",
"Copy": "Kopier",
"Paste": "Lim inn",
"Select all": "Velg alt",
"New document": "Nytt dokument",
"Ok": "OK",
"Cancel": "Avbryt",
"Visual aids": "Visuelle hjelpemidler",
"Bold": "Fet",
"Italic": "Kursiv",
"Underline": "Understrek",
"Strikethrough": "Gjennomstrek",
"Superscript": "Superskript",
"Subscript": "Subskript",
"Clear formatting": "Fjern formatering",
"Align left": "Venstrestill",
"Align center": "Midtstill",
"Align right": "Høyrestill",
"Justify": "Blokkjuster",
"Bullet list": "Punktliste",
"Numbered list": "Nummerert liste",
"Decrease indent": "Reduser innrykk",
"Increase indent": "Øk innrykk",
"Close": "Lukk",
"Formats": "Formater",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Nettleseren støtter ikke direkte tilgang til kopiert innhold. Vennligst bruk Ctrl+X\/C\/V i stedet.",
"Headers": "Overskrifter",
"Header 1": "Overskrift 1",
"Header 2": "Overskrift 2",
"Header 3": "Overskrift 3",
"Header 4": "Overskrift 4",
"Header 5": "Overskrift 5",
"Header 6": "Overskrift 6",
"Headings": "Overskrifter",
"Heading 1": "Overskrift 1",
"Heading 2": "Overskrift 2",
"Heading 3": "Overskrift 3",
"Heading 4": "Overskrift 4",
"Heading 5": "Overskrift 5",
"Heading 6": "Overskrift 6",
"Preformatted": "Preformatert",
"Div": "Div",
"Pre": "Pre",
"Code": "Kode",
"Paragraph": "Avsnitt",
"Blockquote": "Sitatblokk",
"Inline": "På linje",
"Blocks": "Blokker",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Liming er nå i ren-tekst modus. Innhold limt inn vil legges inn som ren tekst til dette valget er skrudd av.",
"Fonts": "Skrifttyper",
"Font Sizes": "Skriftstørrelser",
"Class": "Klasse",
"Browse for an image": "Let etter et bilde",
"OR": "ELLER",
"Drop an image here": "Trekk et bilde hit",
"Upload": "Last opp",
"Block": "Blokk",
"Align": "Juster",
"Default": "Standard",
"Circle": "Sirkel",
"Disc": "Disk",
"Square": "Firkant",
"Lower Alpha": "Små bokstaver (alfa)",
"Lower Greek": "Små bokstaver (gresk)",
"Lower Roman": "Små bokstaver (romersk)",
"Upper Alpha": "Store bokstaver (alfa)",
"Upper Roman": "Store bokstaver (romersk)",
"Anchor...": "Anker ...",
"Name": "Navn",
"Id": "Id",
"Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "ID må starte med en bokstav, etterfulgt av kun bokstaver, tall, bindestreker, punktum, kolon eller understreker.",
"You have unsaved changes are you sure you want to navigate away?": "Du har ulagrede endringer, er du sikker på at du vil navigere bort?",
"Restore last draft": "Gjenopprett siste utkast",
"Special character...": "Spesialtegn ...",
"Source code": "Kildekode",
"Insert\/Edit code sample": "Sett inn\/endre kodeeksempel",
"Language": "Språk",
"Code sample...": "Kodeeksempel ...",
"Color Picker": "Fargevelger",
"R": "R",
"G": "G",
"B": "B",
"Left to right": "Venstre til høyre",
"Right to left": "Høyre til venstre",
"Emoticons...": "Emotikoner ...",
"Metadata and Document Properties": "Metadata og dokumentegenskaper",
"Title": "Tittel",
"Keywords": "Nøkkelord",
"Description": "Beskrivelse",
"Robots": "Roboter",
"Author": "Forfatter",
"Encoding": "Koding",
"Fullscreen": "Fullskjerm",
"Action": "Handling",
"Shortcut": "Snarvei",
"Help": "Hjelp",
"Address": "Adresse",
"Focus to menubar": "Fokus til menylinjen",
"Focus to toolbar": "Fokus til verktøylinjen",
"Focus to element path": "Fokus til elementsti",
"Focus to contextual toolbar": "Fokus til kontekstuell verktøylinje",
"Insert link (if link plugin activated)": "Sett inn lenke (hvis lenke-modulen er aktivert)",
"Save (if save plugin activated)": "Lagre (hvis lagre-modulen er aktivert)",
"Find (if searchreplace plugin activated)": "Finn (hvis søk-og-erstatt-modulen er aktivert)",
"Plugins installed ({0}):": "Moduler installert ({0}): ",
"Premium plugins:": "Premium-moduler:",
"Learn more...": "Lær mer ...",
"You are using {0}": "Du bruker {0}",
"Plugins": "Moduler",
"Handy Shortcuts": "Nyttige snarveier",
"Horizontal line": "Horisontal linje",
"Insert\/edit image": "Sett inn\/endre bilde",
"Image description": "Bildebeskrivelse",
"Source": "Kilde",
"Dimensions": "Dimensjoner",
"Constrain proportions": "Behold proporsjoner",
"General": "Generelt",
"Advanced": "Avansert",
"Style": "Stil",
"Vertical space": "Vertikal avstand",
"Horizontal space": "Horisontal avstand",
"Border": "Ramme",
"Insert image": "Sett inn bilde",
"Image...": "Bilde...",
"Image list": "Bildeliste",
"Rotate counterclockwise": "Roter mot klokken",
"Rotate clockwise": "Roter med klokken",
"Flip vertically": "Vend loddrett",
"Flip horizontally": "Vend vannrett",
"Edit image": "Rediger bilde",
"Image options": "Bildevalg",
"Zoom in": "Zoom inn",
"Zoom out": "Zoom ut",
"Crop": "Beskjær",
"Resize": "Endre størrelse",
"Orientation": "Orientering",
"Brightness": "Lysstyrke",
"Sharpen": "Skarphet",
"Contrast": "Kontrast",
"Color levels": "Fargenivåer",
"Gamma": "Gamma",
"Invert": "Inverter",
"Apply": "Bruk",
"Back": "Tilbake",
"Insert date\/time": "Sett inn dato\/klokkeslett",
"Date\/time": "Dato\/klokkeslett",
"Insert\/Edit Link": "Sett inn\/endre lenke",
"Insert\/edit link": "Sett inn\/endre lenke",
"Text to display": "Tekst som skal vises",
"Url": "URL",
"Open link in...": "Åpne lenke i ...",
"Current window": "Gjeldende vindu",
"None": "Ingen",
"New window": "Nytt vindu",
"Remove link": "Fjern lenke",
"Anchors": "Ankre",
"Link...": "Lenke...",
"Paste or type a link": "Lim inn eller skriv en lenke",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "URLen du skrev inn ser ut til å være en e-postadresse. Vil du legge til det nødvendige prefikset mailto:?",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "URLen du skrev inn ser ut til å være en ekstern lenke. Vil du legge til det nødvendige prefikset http:\/\/?",
"Link list": "Lenkeliste",
"Insert video": "Sett inn video",
"Insert\/edit video": "Sett inn\/endre video",
"Insert\/edit media": "Sett inn\/endre media",
"Alternative source": "Alternativ kilde",
"Alternative source URL": "Alternativ kilde URL",
"Media poster (Image URL)": "Mediaplakat (Bilde URL)",
"Paste your embed code below:": "Lim inn innbyggingskoden under:",
"Embed": "Bygg inn",
"Media...": "Media...",
"Nonbreaking space": "Hardt mellomrom",
"Page break": "Sideskift",
"Paste as text": "Lim inn som tekst",
"Preview": "Forhåndsvisning",
"Print...": "Skriv ut...",
"Save": "Lagre",
"Find": "Finn",
"Replace with": "Erstatt med",
"Replace": "Erstatt",
"Replace all": "Erstatt alle",
"Previous": "Forrige",
"Next": "Neste",
"Find and replace...": "Finn og erstatt...",
"Could not find the specified string.": "Kunne ikke finne den spesifiserte strengen.",
"Match case": "Skill mellom store og små bokstaver",
"Find whole words only": "Finn kun hele ord",
"Spell check": "Stavekontroll",
"Ignore": "Ignorer",
"Ignore all": "Ignorer alle",
"Finish": "Fullfør",
"Add to Dictionary": "Legg til i ordbok",
"Insert table": "Sett inn tabell",
"Table properties": "Tabellegenskaper",
"Delete table": "Slett tabell",
"Cell": "Celle",
"Row": "Rad",
"Column": "Kolonne",
"Cell properties": "Celleegenskaper",
"Merge cells": "Slå sammen celler",
"Split cell": "Del celle",
"Insert row before": "Sett inn rad før",
"Insert row after": "Sett inn rad etter",
"Delete row": "Slett rad",
"Row properties": "Radegenskaper",
"Cut row": "Klipp ut rad",
"Copy row": "Kopier rad",
"Paste row before": "Lim inn rad før",
"Paste row after": "Lim inn rad etter",
"Insert column before": "Sett inn kolonne før",
"Insert column after": "Sett inn kolonne etter",
"Delete column": "Slett kolonne",
"Cols": "Kolonner",
"Rows": "Rader",
"Width": "Bredde",
"Height": "Høyde",
"Cell spacing": "Celleavstand",
"Cell padding": "Cellemarg",
"Show caption": "Vis tittel",
"Left": "Venstre",
"Center": "Midtstilt",
"Right": "Høyre",
"Cell type": "Celletype",
"Scope": "Omfang",
"Alignment": "Justering",
"H Align": "H-Justering",
"V Align": "V-Justering",
"Top": "Topp",
"Middle": "Midten",
"Bottom": "Bunn",
"Header cell": "Overskriftscelle",
"Row group": "Radgruppe",
"Column group": "Kolonnegruppe",
"Row type": "Radtype",
"Header": "Topptekst",
"Body": "Brødtekst",
"Footer": "Bunntekst",
"Border color": "Rammefarge",
"Insert template...": "Sett inn mal ...",
"Templates": "Maler",
"Template": "Mal",
"Text color": "Tekstfarge",
"Background color": "Bakgrunnsfarge",
"Custom...": "Egendefinert ...",
"Custom color": "Egendefinert farge",
"No color": "Ingen farge",
"Remove color": "Fjern farge",
"Table of Contents": "Innholdsfortegnelse",
"Show blocks": "Vis blokker",
"Show invisible characters": "Vis usynlige tegn",
"Word count": "Ordtelling",
"Count": "Antall",
"Document": "Dokument",
"Selection": "Utvalg",
"Words": "Ord",
"Words: {0}": "Ord: {0}",
"{0} words": "{0} ord",
"File": "Fil",
"Edit": "Rediger",
"Insert": "Sett inn",
"View": "Vis",
"Format": "Format",
"Table": "Tabell",
"Tools": "Verktøy",
"Powered by {0}": "Drevet av {0}",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Riktekstområde. Trykk ALT-F9 for meny. Trykk ALT-F10 for verktøylinje. Trykk ALT-0 for hjelp.",
"Image title": "Bildetittel",
"Border width": "Rammetykkelse",
"Border style": "Rammestil",
"Error": "Feil",
"Warn": "Advarsel",
"Valid": "Gyldig",
"To open the popup, press Shift+Enter": "For å åpne popup-vinduet, trykk Shift+Enter",
"Rich Text Area. Press ALT-0 for help.": "Riktekstområde. Trykk ALT-0 for hjelp.",
"System Font": "Systemskrifttype",
"Failed to upload image: {0}": "Kunne ikke laste opp bilde: {0}",
"Failed to load plugin: {0} from url {1}": "Kunne ikke laste inn modul: {0} fra URL {1}",
"Failed to load plugin url: {0}": "Kunne ikke laste inn modul-URL: {0}",
"Failed to initialize plugin: {0}": "Kunne ikke initialisere modul: {0}",
"example": "eksempel",
"Search": "Søk",
"All": "Alle",
"Currency": "Valuta",
"Text": "Tekst",
"Quotations": "Sitater",
"Mathematical": "Matematiske tegn",
"Extended Latin": "Utvidet Latin",
"Symbols": "Symboler",
"Arrows": "Piler",
"User Defined": "Brukerdefinert",
"dollar sign": "Dollartegn",
"currency sign": "Valutategn",
"euro-currency sign": "Eurotegn",
"colon sign": "Colón-tegn",
"cruzeiro sign": "Cruzeiro-tegn",
"french franc sign": "Fransk franc-tegn",
"lira sign": "Lire-tegn",
"mill sign": "Mill-tegn",
"naira sign": "Naira-tegn",
"peseta sign": "Peseta-tegn",
"rupee sign": "Rupitegn",
"won sign": "Won-tegn",
"new sheqel sign": "Ny shekel-tegn",
"dong sign": "Dong-tegn",
"kip sign": "Kip-tegn",
"tugrik sign": "Tugrik-tegn",
"drachma sign": "Drakme-tegn",
"german penny symbol": "Tysk pfennig-symbol",
"peso sign": "Peso-tegn",
"guarani sign": "Guarani-tegn",
"austral sign": "Austral-tegn",
"hryvnia sign": "Hryvnia-tegn",
"cedi sign": "Cedi-tegn",
"livre tournois sign": "Livre tournois-tegn",
"spesmilo sign": "Spesmilo-tegn",
"tenge sign": "Tenge-tegn",
"indian rupee sign": "Indisk rupi-tegn",
"turkish lira sign": "Tyrkisk lire-tegn",
"nordic mark sign": "Nordisk mark-tegn",
"manat sign": "Manat-tegn",
"ruble sign": "Rubel-tegn",
"yen character": "Yen-tegn",
"yuan character": "Yuan-tegn",
"yuan character, in hong kong and taiwan": "Yuan-tegn, i Hong Kong og Taiwan",
"yen\/yuan character variant one": "Yen\/Yuan-tegn, variant én",
"Loading emoticons...": "Laster emotikoner ...",
"Could not load emoticons": "Kunne ikke laste emotikoner",
"People": "Folk",
"Animals and Nature": "Dyr og natur",
"Food and Drink": "Mat og drikke",
"Activity": "Aktivitet",
"Travel and Places": "Reise og steder",
"Objects": "Objekter",
"Flags": "Flagg",
"Characters": "Tegn",
"Characters (no spaces)": "Tegn (uten mellomrom)",
"{0} characters": "{0} tegn",
"Error: Form submit field collision.": "Feil: Kollisjon i skjema-innsendingsfelt.",
"Error: No form element found.": "Feil: Ingen skjemadel funnet.",
"Update": "Oppdater",
"Color swatch": "Fargeprøve",
"Turquoise": "Turkis",
"Green": "Grønn",
"Blue": "Blå",
"Purple": "Lilla",
"Navy Blue": "Marineblå",
"Dark Turquoise": "Mørk turkis",
"Dark Green": "Mørk grønn",
"Medium Blue": "Middels blå",
"Medium Purple": "Middels lilla",
"Midnight Blue": "Midnattsblå",
"Yellow": "Gul",
"Orange": "Oransje",
"Red": "Rød",
"Light Gray": "Lys grå",
"Gray": "Grå",
"Dark Yellow": "Mørk gul",
"Dark Orange": "Mørk oransje",
"Dark Red": "Mørk rød",
"Medium Gray": "Middels grå",
"Dark Gray": "Mørk grå",
"Light Green": "Lys grønn",
"Light Yellow": "Lys gul",
"Light Red": "Lys rød",
"Light Purple": "Lys lilla",
"Light Blue": "Lys blå",
"Dark Purple": "Mørk lilla",
"Dark Blue": "Mørk blå",
"Black": "Svart",
"White": "Hvit",
"Switch to or from fullscreen mode": "Bytt til eller fra fullskjermmodus",
"Open help dialog": "Åpne hjelpedialog",
"history": "historikk",
"styles": "stiler",
"formatting": "formatering",
"alignment": "justering",
"indentation": "innrykk",
"permanent pen": "permanent penn",
"comments": "kommentarer",
"Format Painter": "Kopier format",
"Insert\/edit iframe": "Sett inn\/endre iframe",
"Capitalization": "Kapitalisering",
"lowercase": "små bokstaver",
"UPPERCASE": "STORE BOKSTAVER",
"Title Case": "Stor forbokstav i alle ord",
"Permanent Pen Properties": "Egenskaper for permanent penn",
"Permanent pen properties...": "Egenskaper for permanent penn ...",
"Font": "Skrifttype",
"Size": "Størrelse",
"More...": "Mer ...",
"Spellcheck Language": "Stavekontroll-språk",
"Select...": "Velg ...",
"Preferences": "Innstillinger",
"Yes": "Ja",
"No": "Nei",
"Keyboard Navigation": "Tastaturnavigering",
"Version": "Versjon",
"Anchor": "Anker",
"Special character": "Spesialtegn",
"Code sample": "Kodeeksempel",
"Color": "Farge",
"Emoticons": "Emotikoner",
"Document properties": "Dokumentegenskaper",
"Image": "Bilde",
"Insert link": "Sett inn lenke",
"Target": "Mål",
"Link": "Lenke",
"Poster": "Plakat",
"Media": "Media",
"Print": "Skriv ut",
"Prev": "Forrige",
"Find and replace": "Finn og erstatt",
"Whole words": "Hele ord",
"Spellcheck": "Stavekontroll",
"Caption": "Tittel",
"Insert template": "Sett inn mal"
});